fieldLayouts:
  394e5672-6a26-436c-b7ed-df6f08a14b7e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 387647cb-fc92-4ba0-82cc-001ad6cc2a1e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 585a908e-edef-4144-ac08-830dac3a8b7a # Feature Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ab815606-84e1-4072-8643-55a7afb3a616
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dc571ad6-13bc-4432-9494-a95c462a01b5 # Summary
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 88eacc31-7ca7-4a4a-bb49-a36162b26c72
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fbf36878-aa03-44f2-993c-709684cea188 # Post Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 28aded03-fa30-4335-b68a-1e232a986e2f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6a78c6e9-157a-4563-850e-c6bb81d9e062 # Post Categories
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 076578fa-3bdd-4d0a-a0e8-cb1731ad51ad
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4472e5e4-7717-430d-85d8-2655ed523267
        userCondition: null
handle: post
hasTitleField: true
name: Post
section: b02d46ea-586a-4e25-84b5-b5902c401e85 # Blog
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
