fieldLayouts:
  0e26b663-0211-4c6d-909a-d00983f3acba:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 0ed86d4f-5717-40a5-bebe-c1fc440e9165
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 236ce11f-be8e-48e7-b75e-4c581d3f42dc
        userCondition: null
fs: hardDisk
handle: images
name: Images
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
