columnSuffix: null
contentColumnType: string
fieldGroup: 9ddd186b-26bd-4f9b-82f0-303672c79fa0 # Blog
handle: postContent
instructions: null
name: 'Post Content'
searchable: false
settings:
  contentTable: '{{%matrixcontent_postcontent}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
